import asyncio
import logging
import sys
import os

# Add parent directory to path to import app modules
base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(base_dir)
sys.path.append(os.path.join(base_dir, 'app')) # Add 'app' directory explicitly to path

from app.services.mongodb_service import get_db
from app.services.authority_service import save_mapping_review
import uuid
from datetime import datetime

# Setup logging
logging.basicConfig(level=logging.INFO)

async def trigger_test_review():
    print("🚀 Triggering Test Review Entry...")
    
    entry = {
        "id": str(uuid.uuid4()),
        "case_id": "TEST-BROWSER-VERIFY",
        "issue_type": "alien_invasion_test",
        "submitted_description": "Verification Test: Alien Invasion Detected.",
        "ai_confidence": 0,
        "attempted_mapping": None,
        "current_routed_to": "general",
        "flagged_at": datetime.utcnow().isoformat(),
        "resolved": False,
        "admin_notes": "Generated by Verification Script"
    }
    
    # We can use save_mapping_review directly if we want
    # But let's check if we can verify connection first
    db = await get_db()
    
    # Insert manually to be sure
    await db.authority_mapping_review.insert_one(entry)
    
    print(f"✅ Test entry inserted into 'authority_mapping_review'. ID: {entry['id']}")

if __name__ == "__main__":
    asyncio.run(trigger_test_review())
