# 🚀 SnapFix Enterprise Helm Chart
# 📊 Advanced Kubernetes Deployment for 100,000+ Users
# ☸️ Production-Ready with Auto-Scaling, Monitoring & Security
# 🔧 Multi-Environment Support with GitOps Integration

apiVersion: v2
name: snapfix-enterprise
description: |
  SnapFix Enterprise - Advanced Kubernetes deployment chart for handling 100,000+ concurrent users.
  Features comprehensive auto-scaling, monitoring, security, and multi-environment support.
  
  Key Features:
  - Horizontal Pod Autoscaler (HPA) with custom metrics
  - Vertical Pod Autoscaler (VPA) for resource optimization
  - Advanced security policies and network policies
  - Comprehensive monitoring with Prometheus and Grafana
  - Multi-tier caching with Redis Cluster
  - Database connection pooling and optimization
  - Load balancing with Nginx Ingress
  - GitOps ready with ArgoCD integration
  - Blue-Green and Canary deployment strategies
  - Disaster recovery and backup automation

type: application
version: 2.1.0
appVersion: "2.1.0"

# Chart metadata
home: https://snapfix.enterprise.com
sources:
  - https://github.com/snapfix/snapfix-enterprise
  - https://github.com/snapfix/snapfix-helm-charts

maintainers:
  - name: DevOps Team
    email: devops@snapfix.enterprise.com
    url: https://snapfix.enterprise.com/team
  - name: Platform Engineering
    email: platform@snapfix.enterprise.com
    url: https://snapfix.enterprise.com/platform

keywords:
  - snapfix
  - enterprise
  - scalability
  - microservices
  - kubernetes
  - auto-scaling
  - monitoring
  - security
  - high-availability
  - performance
  - fastapi
  - python
  - redis
  - postgresql
  - mongodb
  - prometheus
  - grafana
  - nginx
  - ingress
  - gitops
  - argocd

# Chart dependencies
dependencies:
  # Redis Cluster for caching and session management
  - name: redis
    version: "17.15.6"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cache
      - session
    import-values:
      - child: auth.password
        parent: redis.password

  # PostgreSQL for primary database
  - name: postgresql
    version: "12.12.10"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
      - primary
    import-values:
      - child: auth.postgresPassword
        parent: postgresql.password

  # MongoDB for document storage
  - name: mongodb
    version: "13.18.5"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
    tags:
      - database
      - document
    import-values:
      - child: auth.rootPassword
        parent: mongodb.password

  # RabbitMQ for message queuing
  - name: rabbitmq
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
    tags:
      - messaging
      - queue
    import-values:
      - child: auth.password
        parent: rabbitmq.password

  # Prometheus for monitoring
  - name: kube-prometheus-stack
    version: "51.9.4"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
    tags:
      - monitoring
      - metrics
      - alerting

  # Grafana for visualization (included in kube-prometheus-stack)
  # - name: grafana
  #   version: "6.60.4"
  #   repository: https://grafana.github.io/helm-charts
  #   condition: monitoring.grafana.enabled
  #   tags:
  #     - monitoring
  #     - visualization

  # Elasticsearch for logging
  - name: elasticsearch
    version: "19.13.13"
    repository: https://charts.bitnami.com/bitnami
    condition: logging.elasticsearch.enabled
    tags:
      - logging
      - search

  # Kibana for log visualization
  - name: kibana
    version: "10.4.8"
    repository: https://charts.bitnami.com/bitnami
    condition: logging.kibana.enabled
    tags:
      - logging
      - visualization

  # Jaeger for distributed tracing
  - name: jaeger
    version: "0.71.14"
    repository: https://jaegertracing.github.io/helm-charts
    condition: tracing.jaeger.enabled
    tags:
      - tracing
      - observability

  # Nginx Ingress Controller
  - name: ingress-nginx
    version: "4.8.3"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.nginx.enabled
    tags:
      - ingress
      - load-balancer

  # Cert-Manager for SSL certificates
  - name: cert-manager
    version: "1.13.2"
    repository: https://charts.jetstack.io
    condition: security.certManager.enabled
    tags:
      - security
      - ssl
      - certificates

  # External Secrets Operator
  - name: external-secrets
    version: "0.9.9"
    repository: https://charts.external-secrets.io
    condition: security.externalSecrets.enabled
    tags:
      - security
      - secrets
      - vault

  # Velero for backup and disaster recovery
  - name: velero
    version: "5.1.4"
    repository: https://vmware-tanzu.github.io/helm-charts
    condition: backup.velero.enabled
    tags:
      - backup
      - disaster-recovery

  # ArgoCD for GitOps
  - name: argo-cd
    version: "5.46.8"
    repository: https://argoproj.github.io/argo-helm
    condition: gitops.argocd.enabled
    tags:
      - gitops
      - deployment
      - cd

  # Istio Service Mesh (optional)
  - name: istio-base
    version: "1.19.3"
    repository: https://istio-release.storage.googleapis.com/charts
    condition: serviceMesh.istio.enabled
    tags:
      - service-mesh
      - security
      - traffic-management

  # Keda for event-driven autoscaling
  - name: keda
    version: "2.12.1"
    repository: https://kedacore.github.io/charts
    condition: autoscaling.keda.enabled
    tags:
      - autoscaling
      - event-driven

# Chart annotations for additional metadata
annotations:
  # Artifact Hub annotations
  artifacthub.io/category: "integration-delivery"
  artifacthub.io/license: "MIT"
  artifacthub.io/prerelease: "false"
  artifacthub.io/operator: "false"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - Added advanced auto-scaling capabilities
    - Enhanced security policies and network policies
    - Improved monitoring and observability stack
    - Added GitOps integration with ArgoCD
    - Enhanced backup and disaster recovery
    - Added service mesh support with Istio
    - Improved multi-environment configuration
    - Added event-driven autoscaling with KEDA
    - Enhanced database connection pooling
    - Added comprehensive health checks
  
  # Custom annotations for CI/CD integration
  snapfix.io/min-kubernetes-version: "1.25.0"
  snapfix.io/max-kubernetes-version: "1.28.x"
  snapfix.io/supported-platforms: "aws,gcp,azure,on-premise"
  snapfix.io/deployment-strategies: "rolling,blue-green,canary"
  snapfix.io/scaling-capabilities: "hpa,vpa,keda"
  snapfix.io/monitoring-stack: "prometheus,grafana,jaeger,elk"
  snapfix.io/security-features: "rbac,network-policies,pod-security,secrets-management"
  snapfix.io/backup-support: "velero,database-backups,persistent-volume-snapshots"
  snapfix.io/gitops-ready: "true"
  snapfix.io/multi-environment: "true"
  snapfix.io/high-availability: "true"
  snapfix.io/disaster-recovery: "true"
  
  # Performance and capacity annotations
  snapfix.io/max-concurrent-users: "100000+"
  snapfix.io/max-requests-per-second: "50000+"
  snapfix.io/max-database-connections: "10000+"
  snapfix.io/cache-hit-ratio: "95%+"
  snapfix.io/response-time-p99: "<200ms"
  snapfix.io/uptime-sla: "99.99%"
  
  # Compliance and governance
  snapfix.io/compliance-standards: "SOC2,GDPR,HIPAA,PCI-DSS"
  snapfix.io/data-encryption: "at-rest,in-transit"
  snapfix.io/audit-logging: "enabled"
  snapfix.io/vulnerability-scanning: "enabled"
  snapfix.io/security-policies: "enforced"

# Chart icon (base64 encoded or URL)
icon: https://snapfix.enterprise.com/assets/logo-chart.png

# Deprecated flag (set to true if this chart version is deprecated)
deprecated: false

# KubeVersion constraint
kubeVersion: ">=1.25.0-0 <1.29.0-0"

# Engine constraint (Helm version)
engine: gotpl

# Chart API version (v2 for Helm 3)
apiVersion: v2