services:
  - type: web
    name: eaiser-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd app && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --loop asyncio --http httptools --access-log --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: /opt/render/project/src/app
      - key: ENV
        value: production
      - key: ENVIRONMENT
        value: production
      - key: PORT
        fromService:
          type: web
          name: eaiser-backend
          property: port
      
      # Email Configuration
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_USER
        value: no-reply@eaiser.ai
      
      # AI Service Configuration
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      
      # MongoDB Configuration - Production Ready
      # Production MongoDB Atlas URI with proper TLS configuration
      - key: MONGO_URI
        value: mongodb+srv://snapfix:Chrishabh100@snapfixcluster.7po8ntf.mongodb.net/snapfix?retryWrites=true&w=majority&appName=SnapFixCluster&tls=true&tlsAllowInvalidCertificates=false
      
      # Fallback MongoDB keys (if MONGO_URI not set)
      - key: MONGODB_URL
        value: mongodb+srv://snapfix:Chrishabh100@snapfixcluster.7po8ntf.mongodb.net/snapfix?retryWrites=true&w=majority&appName=SnapFixCluster&tls=true&tlsAllowInvalidCertificates=false
      - key: MONGODB_URI
        value: mongodb+srv://snapfix:Chrishabh100@snapfixcluster.7po8ntf.mongodb.net/snapfix?retryWrites=true&w=majority&appName=SnapFixCluster&tls=true&tlsAllowInvalidCertificates=false
      - key: MONGODB_NAME
        value: snapfix
      
      # Redis Configuration - Production Ready with Upstash Redis
      # Using Upstash Redis for production caching (free tier available)
      - key: REDIS_URL
        sync: false  # Set this in Render dashboard with your Upstash Redis URL
      
      # Fallback Redis settings for development
      - key: REDIS_HOST
        value: "localhost"  # Fallback for development
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        value: ""  # Will use REDIS_URL in production
      - key: REDIS_DB
        value: 0
      - key: REDIS_SSL
        value: true  # Enable SSL for production Redis
      
      # Performance Configuration - Optimized for Render Production
      - key: MAX_WORKERS
        value: 4
      - key: WORKER_CONNECTIONS
        value: 1000
      - key: KEEPALIVE_TIMEOUT
        value: 5  # Increased for production stability
      - key: MAX_REQUESTS
        value: 2000  # Increased for better throughput
      - key: MAX_REQUESTS_JITTER
        value: 100   # Increased jitter
      
      # AI Service Configuration - Production Timeouts
      - key: AI_TIMEOUT
        value: 15  # Increased timeout for AI service in production
      - key: GEMINI_TIMEOUT
        value: 15  # Specific timeout for Gemini API calls
      
      # Cache Configuration - Production Optimized
      - key: CACHE_TTL
        value: 3600  # 1 hour cache
      - key: SESSION_TIMEOUT
        value: 1800  # 30 minutes
      
      # Security Configuration - Production Ready
      - key: JWT_EXPIRE_MINUTES
        value: 30
      - key: RATE_LIMIT_PER_MINUTE
        value: 1000
      
      # Monitoring Configuration
      - key: METRICS_ENABLED
        value: true
      - key: LOG_LEVEL
        value: INFO
        
    healthCheckPath: /health
    autoDeploy: true